### PR TITLE
ENG-173660: Add docs for include_bio param in agent#index

### PR DESCRIPTION
**Pull request by ananya-ramamurthy**
## Description

- Updated api docs for agent#index endpoint to include `include_bio` param info

## JIRA Link
https://moxiworks.atlassian.net/browse/ENG-173660

## Validation Steps
https://moxiworks-platform.github.io/api.html#agent-index should include `include_bio` param as well.

## PR Checklist
Please ensure steps below have been completed before creating your PR

- [x] A relevant title is added and prefixed with the JIRA ticket number
- [x] Detailed description provided
- [x] JIRA link updated with ticket number
- [x] Validation steps clearly outlined
- [x] Locally tested by the author (if not, explain why)
- [ ] Test coverage (if not, explain why)
- [x] Diff is easy to follow (add clarifying comments where needed)

### CODE REVIEW

**Comment by tomcol** [comment]
@ananya-ramamurthy can you add a pr description?  Perhaps a "before and after" screenshot.  Or actual steps to setup and test (on a mac m1)

**Comment by badran047** [comment]
@ananya-ramamurthy, this PR is going into the `develop` branch in your forked repo. You probably wanted to make the PR against the remote `develop` branch!

**Comment by badran047** [comment]
Nevermind, this is mentioned in the wiki. You are good!

**Comment by badran047** [comment]
> @ananya-ramamurthy, this PR is going into the `develop` branch in your forked repo. You probably wanted to make the PR against the remote `develop` branch!

Nevermind, this is mentioned in the wiki. You are good!

**Review by badran047 — APPROVED** [review]

**Comment by ananya-ramamurthy** [comment]
> @ananya-ramamurthy can you add a pr description? Perhaps a "before and after" screenshot. Or actual steps to setup and test (on a mac m1)

Setup steps have been added to README. See PR here: https://github.com/ananya-ramamurthy/moxiworks-platform.github.io/pull/1/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Review by rjoehatfield — APPROVED** [review]

**Pull request merged**
