### PR TITLE
ENG-174771: Update note attribute info for contact endpoint

### PR DESCRIPTION
**Pull request by ananya-ramamurthy**
## Description

- Updated api docs for contact endpoints to change `note` attribute info

## JIRA Link
https://moxiworks.atlassian.net/browse/ENG-174771

## Validation Steps
https://moxiworks-platform.github.io/api.html#contact description of `note` attribute should change to 
"This is a string which reflects the partner created notes. Agent created notes are not reflected in this attribute.  Any Notes added here will be displayed to the agent in an Activity Log record. Any HTML formatting included will be stripped from the note attribute’s data. This value will be null if no data is available for this attribute. This text field is limited to 3k."

## PR Checklist
Please ensure steps below have been completed before creating your PR

- [x] A relevant title is added and prefixed with the JIRA ticket number
- [x] Detailed description provided
- [x] JIRA link updated with ticket number
- [x] Validation steps clearly outlined
- [x] Locally tested by the author (if not, explain why)
- [ ] Test coverage (if not, explain why)
- [x] Diff is easy to follow (add clarifying comments where needed)

### CODE REVIEW

**Review by badran047 — CHANGES_REQUESTED** [review]
Spotted a couple of typos:
- `This is a string...`
- `...limited to 3k.`

**Review by rjoehatfield — COMMENTED** [review]
@ananya-ramamurthy regarding @badran047's comments.
Just to add a little specificity to Hasan's comment:
Need to change `This is string` to `This is a string` in a number of places.
And `limit to 3k` to `limited to 3k`.

**Comment by ananya-ramamurthy** [comment]
> @ananya-ramamurthy regarding @badran047's comments. Just to add a little specificity to Hasan's comment: Need to change `This is string` to `This is a string` in a number of places. And `limit to 3k` to `limited to 3k`.

Haha yeah not sure why I didn't read it before copy pasting from JIRA ticket.

**Comment by ananya-ramamurthy** [comment]
Updated the text.

**Review by badran047 — APPROVED** [review]

**Pull request merged**
